### ISSUE TITLE
PM3 GUI.exe contains malware

### ISSUE THREAD

**Issue by nvx** [rfidreadermaker/proxmark3-max#2]
PM3 GUI.exe in this repo contains malware

Scan results as per https://www.virustotal.com/gui/file/b867e0a970378770384dab320328d8cd5629ee7e6206f40e4244485eafd2aebb

**Comment by rfidreadermaker** [comment]
I think this is just a false alarm, which may be caused by development tools or operations such as saving imported data. PM3 MAX can be operated using the underlying PROXMARK3, not just the GUI. We guarantee that free software will not contain any form of virus.
